//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HardCP.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HardCP.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0564c79c8d1a2074071b8096500b5d19ba908160a6742f97ff614366520516e8 {
            get {
                object obj = ResourceManager.GetObject("_0564c79c8d1a2074071b8096500b5d19ba908160a6742f97ff614366520516e8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _07bc559e01583e9d9896cd179b0fcf76d514a351ce521a9d4d20b9862643901e {
            get {
                object obj = ResourceManager.GetObject("_07bc559e01583e9d9896cd179b0fcf76d514a351ce521a9d4d20b9862643901e", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0c0a377f0758e25bd644bea7dedafed48a9ac0c82256f041657d44587675be65 {
            get {
                object obj = ResourceManager.GetObject("_0c0a377f0758e25bd644bea7dedafed48a9ac0c82256f041657d44587675be65", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _106289d1ccf3db99dcb4fe85bd6c16f6e656b9f7791d01d0a07f5a0f77c815df {
            get {
                object obj = ResourceManager.GetObject("_106289d1ccf3db99dcb4fe85bd6c16f6e656b9f7791d01d0a07f5a0f77c815df", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1498489_v02_b {
            get {
                object obj = ResourceManager.GetObject("_1498489_v02_b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2370fbcd34fde2e65cd3025a2a33c8dfe0571386f8347cf079af1e81bdb503e6 {
            get {
                object obj = ResourceManager.GetObject("_2370fbcd34fde2e65cd3025a2a33c8dfe0571386f8347cf079af1e81bdb503e6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2aa8fa1b0b93b56aff2790c6e7da7832530da2ce8c1dbc2ef1fed3d9b537e414 {
            get {
                object obj = ResourceManager.GetObject("_2aa8fa1b0b93b56aff2790c6e7da7832530da2ce8c1dbc2ef1fed3d9b537e414", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _34b9617f8668ccafabcf8fa19052e133a17c4625ecf5011dc971217a2c982227 {
            get {
                object obj = ResourceManager.GetObject("_34b9617f8668ccafabcf8fa19052e133a17c4625ecf5011dc971217a2c982227", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _388d249f2647a68a2a5281c68ff6df754843fcf3c433ba22ef257b228b715574 {
            get {
                object obj = ResourceManager.GetObject("_388d249f2647a68a2a5281c68ff6df754843fcf3c433ba22ef257b228b715574", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3cf970a862ab56af21d897d04f02bd7b2304e9072f1945e63b039da056047d74 {
            get {
                object obj = ResourceManager.GetObject("_3cf970a862ab56af21d897d04f02bd7b2304e9072f1945e63b039da056047d74", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3dc301b22c9480add1b0994730dd0fd826f9a23304466f75c0fdf7acbfc241d6 {
            get {
                object obj = ResourceManager.GetObject("_3dc301b22c9480add1b0994730dd0fd826f9a23304466f75c0fdf7acbfc241d6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4510360f5b32f574bbdf98379f29e26430606cf88eaa139b284743cc9fad3938 {
            get {
                object obj = ResourceManager.GetObject("_4510360f5b32f574bbdf98379f29e26430606cf88eaa139b284743cc9fad3938", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4bf1bc030fc168c8b1dd36898cf61643632ed556ecae0542e9b74b93ce3ec526 {
            get {
                object obj = ResourceManager.GetObject("_4bf1bc030fc168c8b1dd36898cf61643632ed556ecae0542e9b74b93ce3ec526", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _515e3d64851e52ca7d28640a8dc74039681330386de90ca24b7b923b6839e8ca {
            get {
                object obj = ResourceManager.GetObject("_515e3d64851e52ca7d28640a8dc74039681330386de90ca24b7b923b6839e8ca", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5275c5779afbaa463aff981fa828c88955c0e9f7b4ea53fe9a19954cca07388a {
            get {
                object obj = ResourceManager.GetObject("_5275c5779afbaa463aff981fa828c88955c0e9f7b4ea53fe9a19954cca07388a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5a5b9518c7985de972a2cea80eb99403ef8e4a5d5c40427103c328883c61a0a2 {
            get {
                object obj = ResourceManager.GetObject("_5a5b9518c7985de972a2cea80eb99403ef8e4a5d5c40427103c328883c61a0a2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5ae25b75d795c924990cd5aef50fe3399d15666e02ee0646ee0b4e768cb2e2f0 {
            get {
                object obj = ResourceManager.GetObject("_5ae25b75d795c924990cd5aef50fe3399d15666e02ee0646ee0b4e768cb2e2f0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6553925de09ef8c0a45bd74d0ba045b5f39f75c3bc686604a3b4ef448f72da4f {
            get {
                object obj = ResourceManager.GetObject("_6553925de09ef8c0a45bd74d0ba045b5f39f75c3bc686604a3b4ef448f72da4f", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6824e8474e1e3130f7c5d7f1a0a6d59038fb4d0c0da02900eefbe9c99da6a74b {
            get {
                object obj = ResourceManager.GetObject("_6824e8474e1e3130f7c5d7f1a0a6d59038fb4d0c0da02900eefbe9c99da6a74b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6f1b20748da8d0959fc1c405e0e41f59faa6a5f3add1858fee1d4cfe58045eda {
            get {
                object obj = ResourceManager.GetObject("_6f1b20748da8d0959fc1c405e0e41f59faa6a5f3add1858fee1d4cfe58045eda", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _7066e7384bbb5d383f2fa61e4958cb56a70f3c231cd76b01f0bb356390c2e8cd {
            get {
                object obj = ResourceManager.GetObject("_7066e7384bbb5d383f2fa61e4958cb56a70f3c231cd76b01f0bb356390c2e8cd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _784cc4980a12f477bfedf2ea75ac4cdc8fbd299f856aeb32f134a3d264882a1d {
            get {
                object obj = ResourceManager.GetObject("_784cc4980a12f477bfedf2ea75ac4cdc8fbd299f856aeb32f134a3d264882a1d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _7d2b7667660f2c68e0e6d556b1d782f28dc0ef6e27a50b067783c7d772b729f1 {
            get {
                object obj = ResourceManager.GetObject("_7d2b7667660f2c68e0e6d556b1d782f28dc0ef6e27a50b067783c7d772b729f1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _8451b9c8016421f0d5765deac693397c5ac9c252c80d3e9bb2f04425cb46f166 {
            get {
                object obj = ResourceManager.GetObject("_8451b9c8016421f0d5765deac693397c5ac9c252c80d3e9bb2f04425cb46f166", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _8700cde5b6249567bf7b9747454bf509af171dbc8e25e723a62fff682016b6d2 {
            get {
                object obj = ResourceManager.GetObject("_8700cde5b6249567bf7b9747454bf509af171dbc8e25e723a62fff682016b6d2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _8a1484fdaaccc24f10665791e0f38854f6604c4add309a469436db9dda49957a {
            get {
                object obj = ResourceManager.GetObject("_8a1484fdaaccc24f10665791e0f38854f6604c4add309a469436db9dda49957a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _8c784cb93790095ecc834ce9015a3dec9bd46b4a67972b525eaeab37c3f9012b {
            get {
                object obj = ResourceManager.GetObject("_8c784cb93790095ecc834ce9015a3dec9bd46b4a67972b525eaeab37c3f9012b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _907bf69866a5592d2a92732fef8e99e4f91d83c3c763c13351dba3b29cfaa5e6 {
            get {
                object obj = ResourceManager.GetObject("_907bf69866a5592d2a92732fef8e99e4f91d83c3c763c13351dba3b29cfaa5e6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap a08a35fb774d2f1ca95d9e60a7b8663f95c522fada5ca215385348e03b73183d {
            get {
                object obj = ResourceManager.GetObject("a08a35fb774d2f1ca95d9e60a7b8663f95c522fada5ca215385348e03b73183d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap a3fb42d41f42c30ce99392f6348d12d0cc9a4ce636e29f77d249dee1296fa5f0 {
            get {
                object obj = ResourceManager.GetObject("a3fb42d41f42c30ce99392f6348d12d0cc9a4ce636e29f77d249dee1296fa5f0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap a7120e3f26f8eed336bcb28b88083d051349dc624ab0403a062cb20b98a616d5 {
            get {
                object obj = ResourceManager.GetObject("a7120e3f26f8eed336bcb28b88083d051349dc624ab0403a062cb20b98a616d5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap a876daf8699263bc99a7688b5da5765a3c8b6cfb81e43fb7f0eb059fe66e3bc2 {
            get {
                object obj = ResourceManager.GetObject("a876daf8699263bc99a7688b5da5765a3c8b6cfb81e43fb7f0eb059fe66e3bc2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aba65beed5332e9ee482a62962833c0c3c3f04ce8d35f14990aac6c291aba799 {
            get {
                object obj = ResourceManager.GetObject("aba65beed5332e9ee482a62962833c0c3c3f04ce8d35f14990aac6c291aba799", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap amd {
            get {
                object obj = ResourceManager.GetObject("amd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap b1b1f24e1992917dbc76a1d702e635bdf83aafc3f0bd72f267ce3830fb08408f {
            get {
                object obj = ResourceManager.GetObject("b1b1f24e1992917dbc76a1d702e635bdf83aafc3f0bd72f267ce3830fb08408f", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap b3db802d951703cbd32895f168140b7a76d3dd817acb7de6b8716d52b77c747a {
            get {
                object obj = ResourceManager.GetObject("b3db802d951703cbd32895f168140b7a76d3dd817acb7de6b8716d52b77c747a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap b4ffd9fedf3ff9bbbebea88b5dd0c0b9568307fa1d30b6476899d0319820399e {
            get {
                object obj = ResourceManager.GetObject("b4ffd9fedf3ff9bbbebea88b5dd0c0b9568307fa1d30b6476899d0319820399e", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap b6af5b05a877b212cc9e16a323c147b1a0d0e659f6882e5a84a0acc9e6519c96 {
            get {
                object obj = ResourceManager.GetObject("b6af5b05a877b212cc9e16a323c147b1a0d0e659f6882e5a84a0acc9e6519c96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap baa33254bfd5938551dbf616d4330495c884f853f4e76e8f3481283ddff11dbc {
            get {
                object obj = ResourceManager.GetObject("baa33254bfd5938551dbf616d4330495c884f853f4e76e8f3481283ddff11dbc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bb5484935a3d270c49125d983fb0a3e03f05e9bd94897b178cc502c5e6673f76 {
            get {
                object obj = ResourceManager.GetObject("bb5484935a3d270c49125d983fb0a3e03f05e9bd94897b178cc502c5e6673f76", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bca25e316641338951aac2625ef1e8e7b25e33415de47b95013fa82ee54b3479 {
            get {
                object obj = ResourceManager.GetObject("bca25e316641338951aac2625ef1e8e7b25e33415de47b95013fa82ee54b3479", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bd50f305ad4da44a46e000d14a7361dc0cb9dd4f71006acf96ebef54a5153b0d {
            get {
                object obj = ResourceManager.GetObject("bd50f305ad4da44a46e000d14a7361dc0cb9dd4f71006acf96ebef54a5153b0d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap beae745d997d5de7c3094e7e926587d72a33b9ab8a29a8516f84193606ce4711 {
            get {
                object obj = ResourceManager.GetObject("beae745d997d5de7c3094e7e926587d72a33b9ab8a29a8516f84193606ce4711", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap build1 {
            get {
                object obj = ResourceManager.GetObject("build1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap build2 {
            get {
                object obj = ResourceManager.GetObject("build2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap c05040f3acd015003f9ce5409de4b901235be8d8e7bd74c9bc2bbdb0206a5f6a {
            get {
                object obj = ResourceManager.GetObject("c05040f3acd015003f9ce5409de4b901235be8d8e7bd74c9bc2bbdb0206a5f6a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap c9974d6c92a2f6c3329c453a00c22081aef22d10df4bb855623c0b558a8dfaf8 {
            get {
                object obj = ResourceManager.GetObject("c9974d6c92a2f6c3329c453a00c22081aef22d10df4bb855623c0b558a8dfaf8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cb9d62f0e3388b9f0ae1d7fa3f04f36c937092d646d352355d727faf34fd43b3 {
            get {
                object obj = ResourceManager.GetObject("cb9d62f0e3388b9f0ae1d7fa3f04f36c937092d646d352355d727faf34fd43b3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cce7f231250f3f54578c764049b1820755d2d1ccffe73d0a713b6463323b52af {
            get {
                object obj = ResourceManager.GetObject("cce7f231250f3f54578c764049b1820755d2d1ccffe73d0a713b6463323b52af", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap d1ff60fa20426f9348212b9759a78103a050c9ca4fcde646f0c950f69af07caf {
            get {
                object obj = ResourceManager.GetObject("d1ff60fa20426f9348212b9759a78103a050c9ca4fcde646f0c950f69af07caf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap d40b11f4fb119f98233a7ff6dd30b74f5cda3c69b3f076d30349ffe73877a448 {
            get {
                object obj = ResourceManager.GetObject("d40b11f4fb119f98233a7ff6dd30b74f5cda3c69b3f076d30349ffe73877a448", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap d5c050579f0a328e446d453646c010da9850a4776cbfd9b880b2b148fe8bc2ad {
            get {
                object obj = ResourceManager.GetObject("d5c050579f0a328e446d453646c010da9850a4776cbfd9b880b2b148fe8bc2ad", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap d7b59ddd06c09e84eabde7374beae138c9dfd190d6b004b5da7b5c5b2299c453 {
            get {
                object obj = ResourceManager.GetObject("d7b59ddd06c09e84eabde7374beae138c9dfd190d6b004b5da7b5c5b2299c453", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dc3941d304d0fc17f8ad0a32134f89eb500d8875eb44a84fd681e95ddabc1a0e {
            get {
                object obj = ResourceManager.GetObject("dc3941d304d0fc17f8ad0a32134f89eb500d8875eb44a84fd681e95ddabc1a0e", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap e23a5707beaaa0a0b866c37cffde7c3a61c643c700fd1be47cdc0dca92509860 {
            get {
                object obj = ResourceManager.GetObject("e23a5707beaaa0a0b866c37cffde7c3a61c643c700fd1be47cdc0dca92509860", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap e3de7268e80c6c29808a80438f5d0ffed82bab5163a5d6ae29784075b4f4f130 {
            get {
                object obj = ResourceManager.GetObject("e3de7268e80c6c29808a80438f5d0ffed82bab5163a5d6ae29784075b4f4f130", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ec66703c3ca04bc499be2515bfb5842ac2206068e906493fc8d0a29d4b9a14cb {
            get {
                object obj = ResourceManager.GetObject("ec66703c3ca04bc499be2515bfb5842ac2206068e906493fc8d0a29d4b9a14cb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap f0209bab84ac654416ae5b1a7652ca08e3bd10355a5c7c2208cda398b6b35467 {
            get {
                object obj = ResourceManager.GetObject("f0209bab84ac654416ae5b1a7652ca08e3bd10355a5c7c2208cda398b6b35467", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap f1ee82d9032c6a2d27d0a375fb3d2d49022f8b9f057bf86185ecabf7d600125a {
            get {
                object obj = ResourceManager.GetObject("f1ee82d9032c6a2d27d0a375fb3d2d49022f8b9f057bf86185ecabf7d600125a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap f1fcea76ac514c06d30bef78d0a4b6bc9bc13259952abcae40ad6349f3b570ba {
            get {
                object obj = ResourceManager.GetObject("f1fcea76ac514c06d30bef78d0a4b6bc9bc13259952abcae40ad6349f3b570ba", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap f5e3e25ee873734c254c67838ff48d667951117aa0121b99c7ed60d703622cd8 {
            get {
                object obj = ResourceManager.GetObject("f5e3e25ee873734c254c67838ff48d667951117aa0121b99c7ed60d703622cd8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fc1ee4a47dc4a1740799e996bf0d478f8908764c5f55f176f6b0bc0ca5f5eef2 {
            get {
                object obj = ResourceManager.GetObject("fc1ee4a47dc4a1740799e996bf0d478f8908764c5f55f176f6b0bc0ca5f5eef2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap intel {
            get {
                object obj = ResourceManager.GetObject("intel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        /// </summary>
        internal static System.Drawing.Icon logo11 {
            get {
                object obj = ResourceManager.GetObject("logo11", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo111 {
            get {
                object obj = ResourceManager.GetObject("logo111", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        /// </summary>
        internal static System.Drawing.Icon logo12 {
            get {
                object obj = ResourceManager.GetObject("logo12", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo121 {
            get {
                object obj = ResourceManager.GetObject("logo121", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SBK0096672_v01_b {
            get {
                object obj = ResourceManager.GetObject("SBK0096672_v01_b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SBK0098401_v01_b {
            get {
                object obj = ResourceManager.GetObject("SBK0098401_v01_b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SBK0113505_v01_b {
            get {
                object obj = ResourceManager.GetObject("SBK0113505_v01_b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SBK0113775_v01_b {
            get {
                object obj = ResourceManager.GetObject("SBK0113775_v01_b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SBK0115228_v01_b {
            get {
                object obj = ResourceManager.GetObject("SBK0115228_v01_b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SBK0116309_v01_b {
            get {
                object obj = ResourceManager.GetObject("SBK0116309_v01_b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Снимок {
            get {
                object obj = ResourceManager.GetObject("Снимок", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
